In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import astropy
import lightkurve as lk
from scipy import *
from astropy import constants as ac
from astropy import units as u

In [2]:
from matplotlib import rcParams
rcParams["savefig.dpi"] = 100
rcParams["figure.dpi"] = 100
rcParams["font.size"] = 20
rcParams["figure.figsize"] = [8, 5]
rcParams["font.family"] = "sans-serif"
rcParams["font.sans-serif"] = ["Computer Modern Sans Serif"]
rcParams["text.usetex"] = True
plt.rcParams['axes.linewidth']=1.5

Loading in lists of targets

In [3]:
candidates = pd.read_csv('/Users/lupitatovar/Cool-Worlds/targets/candidates_temp_cuts.csv')
confirmed = pd.read_csv('/Users/lupitatovar/Cool-Worlds/targets/confirmed_temp_cuts.csv')

In [4]:
stars = pd.read_csv('/Users/lupitatovar/Cool-Worlds/targets/stellar_propoerties.csv')

In [5]:
conf_stars = np.where(stars["Status"].str.contains("Confirmed"))[0]
cand_stars = np.where(stars["Status"].str.contains("Candidate"))[0]

In [6]:
len(stars['st_radius'].values[cand_stars])

35

Defining a function to calculate TSM based on (Kempton et al. 2018) paper

In [7]:
def tsm(sf,Rp,Teq,Mp,Rs,mj):
    #sf = 0.190 (for planets with radii < 1.5 earth radius)
    #sf = 1.26 for planets 1.5<rp<2.75
    tsm_ = sf * ((Rp**3 * Teq) / (Mp * Rs**2)) * 10**(-mj/5)
    return tsm_

Calculating TSM for all the confirmed planets

In [8]:
rp_conf = confirmed['rade'].values             #[Earth radii]
mp_conf = confirmed['masse_est'].values              #[Earth mass, estimate using m/r relationship]
temp_conf = confirmed['T_eff'].values             #effective temperature
rs_conf =  stars['st_radius'].values[conf_stars]   #stellar radii
jmag_conf = stars['Jmag'].values[conf_stars]       #magnitude in j band

In [9]:
print(rp_conf)

[1.72227027 1.8        1.533375   1.6        1.56843636 1.55647059]


In [10]:
tsm_conf = []

for i in range (0,len(confirmed)):
    tsm_temp = tsm(1.26,rp_conf[i],temp_conf[i],mp_conf[i],rs_conf[i],jmag_conf[i])
    tsm_conf = np.append(tsm_conf,tsm_temp)
    print (tsm_conf)

[2.7586628]
[2.7586628  3.65611185]
[2.7586628  3.65611185 2.50550157]
[2.7586628  3.65611185 2.50550157 5.80063999]
[2.7586628  3.65611185 2.50550157 5.80063999 2.6136068 ]
[2.7586628  3.65611185 2.50550157 5.80063999 2.6136068  2.5946604 ]


In [11]:
tsm_conf

array([2.7586628 , 3.65611185, 2.50550157, 5.80063999, 2.6136068 ,
       2.5946604 ])

In [12]:
confirmed

Unnamed: 0           name     hostname     insol      period       T_eff  \
0           2  Kepler-1544 b  Kepler-1544  0.774587  168.811174  248.740874   
1           4   Kepler-296 f   Kepler-296  0.620000   63.336270  212.794092   
2           6    Kepler-62 f    Kepler-62  0.509360  267.291000  223.993704   
3           8  Kepler-1652 b  Kepler-1652  0.810000   38.097220  253.928767   
4           9   Kepler-441 b   Kepler-441  0.241811  207.248200  185.929645   
5          10  Kepler-1229 b  Kepler-1229  0.629999   86.828989  236.218911   

       rade   semi_au  masse_est  eccen  st_log_lum discoverymethod  \
0  1.722270  0.539467   3.613241   0.00      -0.647          Kepler   
1  1.800000  0.255000   3.894446   0.33      -1.569          Kepler   
2  1.533375  0.722749   2.966459   0.00      -0.575          Kepler   
3  1.600000  0.165400   3.188594   0.00      -1.638          Kepler   
4  1.568436  0.558807   3.082536   0.10      -1.122          Kepler   
5  1.556471  0.315740   3.042715   0.00      -1.202          Kepler   

        H_Tidal       H_Radio       H_Total  
0  0.000000e+00  2.966220e+14  2.966220e+14  
1  2.045600e+13  3.386230e+14  3.590790e+14  
2  0.000000e+00  2.093360e+14  2.093360e+14  
3  0.000000e+00  2.378260e+14  2.378260e+14  
4  2.515201e+09  2.240270e+14  2.240290e+14  
5  0.000000e+00  2.189380e+14  2.189380e+14

In [13]:
confirmed.insert(15,'TSM',tsm_conf)

In [14]:
confirmed

Unnamed: 0           name     hostname     insol      period       T_eff  \
0           2  Kepler-1544 b  Kepler-1544  0.774587  168.811174  248.740874   
1           4   Kepler-296 f   Kepler-296  0.620000   63.336270  212.794092   
2           6    Kepler-62 f    Kepler-62  0.509360  267.291000  223.993704   
3           8  Kepler-1652 b  Kepler-1652  0.810000   38.097220  253.928767   
4           9   Kepler-441 b   Kepler-441  0.241811  207.248200  185.929645   
5          10  Kepler-1229 b  Kepler-1229  0.629999   86.828989  236.218911   

       rade   semi_au  masse_est  eccen  st_log_lum discoverymethod  \
0  1.722270  0.539467   3.613241   0.00      -0.647          Kepler   
1  1.800000  0.255000   3.894446   0.33      -1.569          Kepler   
2  1.533375  0.722749   2.966459   0.00      -0.575          Kepler   
3  1.600000  0.165400   3.188594   0.00      -1.638          Kepler   
4  1.568436  0.558807   3.082536   0.10      -1.122          Kepler   
5  1.556471  0.315740   3.042715   0.00      -1.202          Kepler   

        H_Tidal       H_Radio       H_Total       TSM  
0  0.000000e+00  2.966220e+14  2.966220e+14  2.758663  
1  2.045600e+13  3.386230e+14  3.590790e+14  3.656112  
2  0.000000e+00  2.093360e+14  2.093360e+14  2.505502  
3  0.000000e+00  2.378260e+14  2.378260e+14  5.800640  
4  2.515201e+09  2.240270e+14  2.240290e+14  2.613607  
5  0.000000e+00  2.189380e+14  2.189380e+14  2.594660

In [15]:
#confirmed.to_csv('/Users/lupitatovar/Cool-Worlds/targets/confirmed_tsm.csv')

Calculating TSM for all of the candidates

In [16]:
rp_cand = candidates['Radius'].values             #[Earth radii]
mp_cand = candidates['masse_est'].values              #[Earth mass, estimate using m/r relationship]
temp_cand = candidates['T_eff'].values             #effective temperature
rs_cand =  stars['st_radius'].values[cand_stars]   #stellar radii
jmag_cand = stars['Jmag'].values[cand_stars]       #magnitude in j band

In [17]:
tsm_cand = []

for i in range (0,len(candidates)):
    tsm_temp2 = tsm(1.26,rp_cand[i],temp_cand[i],mp_cand[i],rs_cand[i],jmag_cand[i])
    tsm_cand = np.append(tsm_cand,tsm_temp2)
    print (tsm_temp2)

2.6276495343022037
1.4013438943977512
0.839123963396286
1.533627994338674
1.5207631245030278
1.8836854795644469
1.1341439780554852
1.6593738896313124
1.6552748789954765
1.1813498334989512
1.8957017517268229
1.2539558606294596
2.402928896286327
2.215981740947318
1.0233562870313442
0.796798268209471
1.5068859044417853
2.2534284151509483
1.1872818252639026
1.2944378225900737
1.5184480314928381
2.4275167857984097
1.1726694983915869
3.8505970259189857
1.4984709146114947
1.6262722823327929
1.125112555686863
1.183850281430631
2.7487811903045585
1.3906284079466082
0.7331447846443261
25.6208823517275
35.15844003997162
32.477348023133246
23.33617206013681


In [18]:
tsm_cand

array([ 2.62764953,  1.40134389,  0.83912396,  1.53362799,  1.52076312,
        1.88368548,  1.13414398,  1.65937389,  1.65527488,  1.18134983,
        1.89570175,  1.25395586,  2.4029289 ,  2.21598174,  1.02335629,
        0.79679827,  1.5068859 ,  2.25342842,  1.18728183,  1.29443782,
        1.51844803,  2.42751679,  1.1726695 ,  3.85059703,  1.49847091,
        1.62627228,  1.12511256,  1.18385028,  2.74878119,  1.39062841,
        0.73314478, 25.62088235, 35.15844004, 32.47734802, 23.33617206])

In [19]:
candidates.insert(14,'TSM',tsm_cand)

In [20]:
candidates

Unnamed: 0               name        hostname  Insolation      Period  \
0            0        KOI-4427.01     KIC 4172805    0.318849  147.661729   
1            1        KOI-4848.01     KIC 9005321    0.160519  384.696100   
2            2        KOI-7716.01     KIC 5097856    0.434274  483.364050   
3            4        KOI-5087.01     KIC 4770798    0.332875  651.074310   
4            5        KOI-5227.01     KIC 6034834    0.598982  371.564920   
5            6        KOI-5236.01     KIC 6067545    0.811569  550.865140   
6            7        KOI-5130.01     KIC 5166811    0.430720  370.059180   
7            8        KOI-5408.01     KIC 7631138    0.354582  415.748785   
8            9        KOI-5789.01    KIC 10387792    0.319386  383.262170   
9           10        KOI-5798.01    KIC 10487228    0.403587  318.258580   
10          11        KOI-5556.01     KIC 8656535    0.331693  631.991160   
11          12        KOI-5810.01    KIC 10581308    0.545106  425.593391   
12          15        KOI-5609.01     KIC 9079671    0.279401  535.151500   
13          16        KOI-5616.01     KIC 9114614    0.151224  441.619190   
14          17        KOI-5755.01    KIC 10007916    0.458060  388.671550   
15          18        KOI-5506.01     KIC 8352009    0.822176  641.602040   
16          19        KOI-5387.01     KIC 7416016    0.225947  297.782820   
17          20        KOI-5389.01     KIC 7416646    0.536408  365.739893   
18          21        KOI-5643.01     KIC 9220614    0.263029  570.018860   
19          23        KOI-5948.01    KIC 12007270    0.715158  398.513120   
20          24        KOI-5949.01    KIC 12009917    0.694553  559.785594   
21          25        KOI-5971.01    KIC 12418418    0.117380  493.305720   
22          26        KOI-5978.01    KIC 12734110    0.458397  364.181290   
23          27        KOI-5870.01    KIC 11129145    0.713900  132.114000   
24          30        KOI-2281.02     KIC 9221517    0.281633  455.274050   
25          32        KOI-7470.01    KIC 11671646    0.401260  392.501150   
26          33        KOI-6343.01     KIC 3548622    0.615537  569.450510   
27          34        KOI-7591.01     KIC 8297319    0.301194  328.322110   
28          37        KOI-7923.01     KIC 9084569    0.429235  395.131380   
29          39        KOI-8047.01    KIC 11294822    0.383837  302.349710   
30          40        KOI-7953.01     KIC 9650579    0.691632  432.969050   
31          41  EPIC 246711015.01  EPIC 246711015    0.554112   13.284219   
32          42  EPIC 246711015.02  EPIC 246711015    0.248873   24.213117   
33          43         TOI-715.01   TIC 271971130    0.726103   19.287972   
34          46        TOI-4328.01    TIC 77175217    0.122511  703.793670   

         T_eff    Radius  masse_est   semi_au  st_log_lum Discovery  \
0   199.239771  1.797673   3.885904  0.447412   -1.195000    Kepler   
1   167.826873  1.880000   4.192848  0.903101   -0.883000    Kepler   
2   215.238882  1.503482   2.868943  1.153766   -0.238000    Kepler   
3   201.395598  1.141911   1.563745  1.441648   -0.160000    Kepler   
4   233.256197  1.611944   3.229113  0.967816   -0.251000    Kepler   
5   251.658130  1.921435   4.350944  1.334558    0.160000    Kepler   
6   214.797110  1.900000   4.268858  0.938774   -0.420683    Kepler   
7   204.601495  1.710821   3.572556  1.034289   -0.421000    Kepler   
8   199.323573  1.532865   2.964783  0.944805   -0.545000    Kepler   
9   211.331357  1.963136   4.512475  0.834702   -0.551000    Kepler   
10  201.216552  1.608549   3.217573  1.393580   -0.191000    Kepler   
11  227.824273  1.395906   2.529190  1.080835   -0.196000    Kepler   
12  192.768716  1.489459   2.823660  1.208888   -0.389000    Kepler   
13  165.342608  1.894865   4.249288  0.990124   -0.829000    Kepler   
14  218.127468  1.503236   2.868146  0.980705   -0.356000    Kepler   
15  252.476476  1.992590   4.628022  1.556028    0.299000    Kepler   
16  182.802162  1.352441

In [21]:
#candidates.to_csv('/Users/lupitatovar/Cool-Worlds/targets/cadidates_tsm.csv')